SELECT  ?v4 ?v6 ?v3 ?v8 ?v7 ?v2 ?v5 ?v0 ?v1 ?v9
WHERE
  { ?v2  <http://schema.org/location>  <http://yago-knowledge.org/resource/Moscow> ;
         <http://schema.org/subOrganization>  ?v3 .
    ?v3  <http://schema.org/parentOrganization>  ?v8 .
    ?v7  <http://schema.org/subOrganization>  ?v3 .
    ?v8  <http://schema.org/foundingDate>  ?v9 .
    ?v4  <http://schema.org/parentOrganization>  ?v7 ;
         <http://schema.org/url>  ?v6 ;
         <http://schema.org/logo>  ?v5 .
    ?v0  <http://schema.org/memberOf>  ?v2 ;
         <http://schema.org/givenName>  ?v1
  }

