SELECT  ?v0 ?v3 ?v4 ?v2 ?v1
WHERE
  { ?v0  <http://schema.org/worksFor>  ?v2 ;
         <http://schema.org/birthDate>  ?v3 ;
         <http://schema.org/location>  ?v1 ;
         <http://schema.org/givenName>  ?v4
  }

