SELECT  ?v0 ?v1 ?v5 ?f ?v4 ?v3
WHERE
  { ?f   <http://schema.org/hasPart>  ?v0 .
    ?v0  <http://schema.org/isPartOf>  ?v1 ;
         <http://schema.org/productionCompany>  ?v4 ;
         <http://schema.org/actor>  ?v3 .
    ?v1  <http://schema.org/alternateName>  ?v5
  }

