SELECT  ?v0 ?v7 ?v9 ?v8 ?v1 ?v6 ?v4 ?v3 ?v5
WHERE
  { ?v0  a                     <http://yago-knowledge.org/resource/Author> ;
         <http://schema.org/birthDate>  ?v4 ;
         <http://schema.org/knowsLanguage>  ?v7 ;
         <http://schema.org/alumniOf>  ?v9 ;
         <http://schema.org/alumniOf>  ?v6 ;
         <http://schema.org/givenName>  ?v5 ;
         <http://schema.org/hasOccupation>  ?v3 ;
         <http://schema.org/nationality>  ?v8 ;
         <http://schema.org/alternateName>  ?v1
  }

