SELECT  ?v0 ?v3 ?v2 ?v4
WHERE
  { ?v0  <http://schema.org/producer>  ?v4 ;
         a                     <http://schema.org/Movie> ;
         <http://schema.org/genre>  ?v3 ;
         <http://schema.org/actor>  ?v2
  }

