PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub:  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT * WHERE {
?Y rdf:type <http://swat.cse.lehigh.edu/onto/univ-bench.owl#FullProfessor> .
?Y <http://swat.cse.lehigh.edu/onto/univ-bench.owl#memberOf> ?dept .
?Y <http://swat.cse.lehigh.edu/onto/univ-bench.owl#worksFor> ?uni .
?Y <http://swat.cse.lehigh.edu/onto/univ-bench.owl#teacherOf> ?Z .
}