SELECT  *
WHERE
  { ?Y  a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#FullProfessor> ;
        <http://swat.cse.lehigh.edu/onto/univ-bench.owl#teacherOf>  ?Z .
    ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#advisor>  ?Y ;
        a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#UndergraduateStudent> .
    ?Z  a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course> .
    ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#takesCourse>  ?Z
  }

