PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  
PREFIX ub: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT *  WHERE {
?X <http://swat.cse.lehigh.edu/onto/univ-bench.owl#advisor> ?Y .
?Y <http://swat.cse.lehigh.edu/onto/univ-bench.owl#teacherOf> ?Z .
?X <http://swat.cse.lehigh.edu/onto/univ-bench.owl#takesCourse> ?Z .
?X rdf:type <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Student> .
?Y rdf:type <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Faculty> .
?Z rdf:type <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course> .
}