PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub:  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT * WHERE {
?H <http://swat.cse.lehigh.edu/onto/univ-bench.owl#headOf> ?D .
?H <http://swat.cse.lehigh.edu/onto/univ-bench.owl#teacherOf> ?C .
?X <http://swat.cse.lehigh.edu/onto/univ-bench.owl#teachingAssistantOf> ?C .
?X <http://swat.cse.lehigh.edu/onto/univ-bench.owl#degreeFrom> ?U .
?D <http://swat.cse.lehigh.edu/onto/univ-bench.owl#subOrganizationOf> ?U .
?U rdf:type <http://swat.cse.lehigh.edu/onto/univ-bench.owl#University> .
}
