PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub:  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT * WHERE {
	?X ub:degreeFrom ?U .
    ?X rdf:type ub:GraduateStudent .
	?X ub:advisor ?A .
	?A rdf:type ub:FullProfessor .
	?A ub:teacherOf ?C .
	?C rdf:type ub:GraduateCourse .
	?Y ub:takesCourse ?C .
	?Y rdf:type ub:GraduateStudent .
	?U ub:hasAlumnus ?Y .
}
