PREFIX ub: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT  ?S1 ?P1 ?S2 ?C1 ?C2 ?C3 WHERE {
    ?S2 ub:teachingAssistantOf ?C2 .
    ?P1 ub:teacherOf ?C2 .
    ?P1 ub:teacherOf ?C1 .
    ?S2 ub:takesCourse ?C1 .
    ?S1 ub:takesCourse ?C1 .
    ?S1 ub:takesCourse ?C3 .
    ?S2 ub:takesCourse ?C3 .
}