PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub:  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT * WHERE {
	?X ub:advisor ?A .
	?A ub:teacherOf ?C .
	?X ub:takesCourse ?C .
	?A ub:headOf ?D .
	?D ub:subOrganizationOf ?U .
	?U ub:name ?name .
}
