PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub:  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT * WHERE {
	?D ub:subOrganizationOf ?U .
	?P ub:worksFor ?D .
	?P ub:teacherOf ?C .
	?X ub:takesCourse ?C .
	?C rdf:type ub:GraduateCourse .
	?X ub:degreeFrom ?U .
}
