PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT ?X ?Z ?Y ?U WHERE {
    ?X ub:worksFor ?Z .
    ?Z ub:subOrganizationOf ?U .
    ?Y ub:undergraduateDegreeFrom ?U .
    ?Y ub:advisor ?X
}