PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub:  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT * WHERE {
	?X rdf:type ub:Professor .
	?X ub:worksFor ?D .
	?D ub:subOrganizationOf <http://www.University0.edu> .
	?X ub:teacherOf ?C .
	?C ub:name ?name .
	?C rdf:type ub:GraduateCourse .
}
