SELECT  ?X ?name ?A ?D ?C ?C1 ?S
WHERE
  { ?D   <http://swat.cse.lehigh.edu/onto/univ-bench.owl#subOrganizationOf>  <http://www.University0.edu> .
    ?A   <http://swat.cse.lehigh.edu/onto/univ-bench.owl#memberOf>  ?D ;
         <http://swat.cse.lehigh.edu/onto/univ-bench.owl#teacherOf>  ?C .
    ?S   <http://swat.cse.lehigh.edu/onto/univ-bench.owl#advisor>  ?A ;
         <http://swat.cse.lehigh.edu/onto/univ-bench.owl#teachingAssistantOf>  ?C1 .
    ?C   a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course> .
    ?C1  a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course> .
    ?X   <http://swat.cse.lehigh.edu/onto/univ-bench.owl#takesCourse>  ?C ;
         <http://swat.cse.lehigh.edu/onto/univ-bench.owl#name>  ?name ;
         a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Student>
  }

