SELECT  ?X ?Y1 ?Y2 ?Y3
WHERE
  {
      { { { { ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#worksFor>  <http://www.Department0.University0.edu> .
              { ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#emailAddress>  ?Y2 .}
            }
            { ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#name>  ?Y1 .}
          }
          { ?X  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor> .}
        }
        { ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#telephone>  ?Y3 .}
      }
  }