SELECT  *
WHERE
  {
      { { ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#degreeFrom>  ?U .
          { ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#advisor>  ?A .}
        }
        { ?X  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateStudent> .}
      }
  }
