PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub:  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT * WHERE {
?X rdf:type <http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateStudent> .
?X <http://swat.cse.lehigh.edu/onto/univ-bench.owl#advisor> ?A .
?X <http://swat.cse.lehigh.edu/onto/univ-bench.owl#degreeFrom> ?U .

}