SELECT  *
WHERE
  { ?v1  <http://schema.org/language>  <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> ;
         <http://db.uwaterloo.ca/~galuc/wsdbm/hits>  ?v6 ;
         <http://schema.org/url>  ?v5 .
    ?v0  <http://xmlns.com/foaf/homepage>  ?v1 ;
         <http://schema.org/contentSize>  ?v8 ;
         <http://schema.org/description>  ?v4 .
    ?v2  <http://purl.org/goodrelations/includes>  ?v0 .
    ?v7  <http://db.uwaterloo.ca/~galuc/wsdbm/likes>  ?v0 .
    ?v0  <http://ogp.me/ns#tag>  ?f
  }

