SELECT  ?v0 ?f ?v1 ?v7 ?v5 ?v2 ?v4 ?v6
WHERE
  { ?v0  <http://schema.org/caption>  ?v4 ;
         <http://xmlns.com/foaf/homepage>  ?v1 ;
         <http://ogp.me/ns#title>  ?v2 ;
         <http://schema.org/description>  ?v5 .
    ?v1  <http://db.uwaterloo.ca/~galuc/wsdbm/hits>  ?v7 ;
         <http://schema.org/url>  ?v6 .
    ?v0  <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre>  ?f
  }

