SELECT * WHERE {
	?v0 <http://ogp.me/ns#tag> ?f .	
	?v0 <http://xmlns.com/foaf/homepage> ?v1 .
	?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language0> .
	?v2 <http://purl.org/goodrelations/includes> ?v0 .
	?v0 <http://schema.org/description> ?v4 .
	?v0 <http://schema.org/contentSize> ?v8 .
	?v1 <http://schema.org/url> ?v5 .
	?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hits> ?v6 .
	?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .
}

#4.307239143748278E7