SELECT * WHERE {
	?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?z .
	?v0 <http://schema.org/caption> ?v2 .
	?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .
	?v0 <http://schema.org/publisher> ?v4 .
}

#338882.0361521959