SELECT  ?v3 ?v4 ?v5 ?v0 ?f
WHERE
  { ?v3  <http://schema.org/trailer>  ?v4 ;
         a                     <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> ;
         <http://schema.org/keywords>  ?v5 ;
         <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre>  ?v0 .
    ?v0  <http://ogp.me/ns#tag>  ?f
  }

