SELECT  ?Z ?Y ?dept ?X ?uni ?courseName
WHERE
  { ?Y  a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#FullProfessor> ;
        <http://swat.cse.lehigh.edu/onto/univ-bench.owl#worksFor>  ?uni ;
        <http://swat.cse.lehigh.edu/onto/univ-bench.owl#memberOf>  ?dept ;
        <http://swat.cse.lehigh.edu/onto/univ-bench.owl#teacherOf>  ?Z .
    ?Z  a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course> ;
        <http://swat.cse.lehigh.edu/onto/univ-bench.owl#name>  ?courseName .
    ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#takesCourse>  ?Z ;
        <http://swat.cse.lehigh.edu/onto/univ-bench.owl#advisor>  ?Y ;
        a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#UndergraduateStudent>
  }

