PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX yago: <http://yago-knowledge.org/resource/>
SELECT * WHERE {
?v4 <http://schema.org/partOfSeries> ?v5 .
?v5 <http://schema.org/isBasedOn> ?v0 .
?v0 <http://schema.org/duration> ?v1 .
?v0 <http://schema.org/genre> ?f .
?v0 <http://schema.org/actor> ?v2 .
?v5 <http://schema.org/alternateName> ?v6 .
}