PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX yago: <http://yago-knowledge.org/resource/>
SELECT * WHERE {
?v0 rdf:type <http://yago-knowledge.org/resource/Twin> .
?v0 <http://schema.org/birthDate> ?v4 .
?v0 <http://schema.org/givenName> ?v5 .
?v0 <http://schema.org/knowsLanguage> ?v7 .
?v0 <http://schema.org/nationality> ?v8 .
?v0 <http://schema.org/alumniOf> ?v6 .
?v0 <http://schema.org/alumniOf> ?v9 .
?v0 <http://schema.org/hasOccupation> ?v3 .
?v0 <http://schema.org/alternateName> ?v1 .
}