PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT * WHERE {
?v0 <http://schema.org/producer> ?v4 .
?v0 <http://schema.org/genre> ?v3 .
?v0 rdf:type <http://schema.org/Movie> .
?v0 <http://schema.org/actor> ?v2 .
}