PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX yago: <http://yago-knowledge.org/resource/>
SELECT * WHERE {
?v3 <http://schema.org/actor> ?v0 .
?v0 <http://schema.org/givenName> ?v2 .
?v0 <http://schema.org/nationality> <http://yago-knowledge.org/resource/United_States> .
?v0 <http://schema.org/hasOccupation> ?f .
}
