SELECT  ?X ?Z ?Y
WHERE
  { ?Y  a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#University> .
    ?Z  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#subOrganizationOf>  ?Y ;
        a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Department> .
    ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#memberOf>  ?Z ;
        a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateStudent> ;
        <http://swat.cse.lehigh.edu/onto/univ-bench.owl#undergraduateDegreeFrom>  ?Y
  }

