SELECT  ?X ?Y ?Z ?V ?U ?W
WHERE
  { ?U  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#teachingAssistantOf>  ?V .
    ?Z  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#teacherOf>  ?V .
    ?U  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#takesCourse>  ?W .
    ?Z  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#teacherOf>  ?Y .
    ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#takesCourse>  ?Y ;
        <http://swat.cse.lehigh.edu/onto/univ-bench.owl#takesCourse>  ?W
  }

