SELECT  ?Y ?Z ?X
WHERE
  { ?Y  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#subOrganizationOf>  ?Z .
    ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#worksFor>  ?Y ;
        a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Faculty> ;
        <http://swat.cse.lehigh.edu/onto/univ-bench.owl#degreeFrom>  ?Z
  }

