SELECT  ?v1 ?v7 ?v0 ?v5 ?v6 ?v2 ?v4 ?f
WHERE
  { ?v0  <http://schema.org/about>  ?v5 ;
         <http://schema.org/duration>  ?v2 ;
         <http://schema.org/musicBy>  ?v4 ;
         <http://schema.org/genre>  ?f ;
         <http://schema.org/actor>  ?v1 .
    ?v1  <http://schema.org/memberOf>  ?v7 ;
         <http://schema.org/alternateName>  ?v6
  }

