SELECT  ?v2 ?v0 ?v1 ?v7 ?v8 ?v4 ?v5 ?v6 ?f
WHERE
  { ?v1  <http://schema.org/nationality>  <http://yago-knowledge.org/resource/United_Kingdom> ;
         <http://schema.org/url>  ?v5 .
    ?v0  <http://schema.org/actor>  ?v1 .
    ?v2  <http://schema.org/partOfSeries>  ?v0 .
    ?v7  <http://schema.org/partOfSeries>  ?v0 .
    ?v0  <http://schema.org/producer>  ?f ;
         <http://schema.org/datePublished>  ?v4 ;
         <http://schema.org/genre>  ?v8 .
    ?v1  <http://schema.org/alternateName>  ?v6
  }

