SELECT  ?X
WHERE
  { ?X  <http://swat.cse.lehigh.edu/onto/univ-bench.owl#memberOf>  <http://www.Department0.University0.edu> ;
        a                     <http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person>
  }

